version: '3'
services:
  storage:
    image: season/fastdfs
    command: storage
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    container_name: storage
    environment:
    - TRACKER_SERVER=10.0.228.153:22122
    volumes:
    # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
    - ~/fdfs-storage/storage/:/fastdfs/storage/
    #- ./storage/:/fastdfs/store_path
    - ~/fdfs-storage/config/:/fdfs_conf/
    # 网络模式为host，可不暴露端口，即直接使用宿主机的网络端口，只适用于linux系统
    network_mode: host
    tty: true
